version: '3'
services: 
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes: 
            - ./backend:/code
            - ./backend/logs/web:/logs
        ports:
            - 8000:8000
        env_file: 
            - backend/.env
        environment: 
            - LOGS_ROOT=/logs
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports:
            - 4200:4200
        volumes:
            - /opt/app/node_modules
            - ./frontend:/opt/app