version: '3'
services: 
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes: 
            - ./backend:/code
            - ./backend/logs/web:/logs
        ports:
            - 8000:8000
        env_file: 
            - backend/.env
        environment: 
            - LOGS_ROOT=/logs