version: '3'
services: 
    db:
        image: postgres
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - 8081:80
        volumes:
            - static_vol:/var/www/static/
        depends_on: 
            - frontend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes: 
            - ./backend:/code
            - ./backend/logs/web:/logs
            - static_vol:/code/static
        ports:
            - 8000:8000
        env_file: 
            - backend/.env.dev
        environment: 
            - LOGS_ROOT=/logs
            - ENV_PATH=./.env.dev
        command: python manage.py runserver 0.0.0.0:8000
        depends_on: 
            - db
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports:
            - 4200:4200
        volumes:
            - /opt/app/node_modules
            - ./frontend:/opt/app

volumes:
    static_vol: