version: '3'
services: 
    db:
        image: postgres
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes: 
            - ./backend:/code
            - ./backend/logs/web:/logs
            - static_vol:/code/static
        ports:
            - 8000:8000
        env_file: 
            - backend/.env
        environment: 
            - LOGS_ROOT=/logs
            - ENV_PATH=./.env
        depends_on: 
            - db
        command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 conf.wsgi"
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - static_vol:/var/www/static/
        depends_on:
            - backend


volumes:
    static_vol: