# Generated by Django 3.1.2 on 2020-10-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0002_auto_20201002_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='core',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='premium',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
